language: node_js

node_js:
  - "10"
  - "11"
  - "12"

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
    - /^feature/.*$/
    - /^hotfix/.*$/

before_install:
  - npm install

script:
  - npm run bs
  - npm run lint
  - npm run test
  - npm run build

# after_success:
#   - ./bin/build-deploy-docs.sh

notifications:
  email: false
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
