language: node_js

node_js:
  - "10"
  - "11"
  - "12"

branches:
  only:
    - master
    - develop
    - /^release/.*$/
    - /^feature/.*$/
    - /^hotfix/.*$/
    - /^snyk-fix-*$/

before_install:
  - npm install

script:
  - npm run bs
  - npm run build
  - npm run lint
  - npm run test

# after_success:
#   - ./bin/npm-github-push.sh

notifications:
  email: false
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
